### ISSUE TITLE
Overloads of CreateAsync method - param name suggestion

### ISSUE THREAD

**Issue by anand-rengasamy** [Azure-Samples/active-directory-dotnet-windowsphone-8.1#2]
CreateAsync (string authority)  
This does validation of Authority. Better way to convey this is – overload methods having param as ignoreAuthorityValidation.
                  CreateAsync(string authority)
                  CreateAsync(string authority, bool ignoreAuthorityValidation)
 Looking at these 2 overloads I can clearly tell that if I choose (2), I am ignoring authority validation whereas in (1) it is not.

**Comment by jmprieur** [comment]
Archiving this sample
