### ISSUE TITLE
documentation Comments issues

### ISSUE THREAD

**Issue by anand-rengasamy** [Azure-Samples/active-directory-dotnet-windowsphone-8.1#3]
1) There is no method summary comments for ‘ContinueAcquireToken’. Also no comments about params and return value
2) AcquireTokenByRefreshTokenAsync – Can we add a summary comment that this is not going cache the tokens?
3)    AcquireTokenAndContinue – 
        // Returns:
        //     It contains Access Token, Refresh Token and the Access Token's expiration
        //     time.
 May be we should say It returns nothing. ContinueAcquireToken which will be called subsequently returns AuthenticationResult which contains Access Token, Refresh Token and the Access Token's expiration time.

**Comment by jmprieur** [comment]
Archiving this sample
