### ISSUE TITLE
redirectURI changes when crating a signed appx for company app distribution

### ISSUE THREAD

**Issue by m-bene** [Azure-Samples/active-directory-dotnet-windowsphone-8.1#5]
Created the sample, works OK both in the emulator and when deployed to a device using visual studio.

Now I want to distribute this app in our company as described here http://msdn.microsoft.com/en-us/library/windows/apps/jj206943%28v=vs.105%29.aspx:

Create appx package, sign using BuildMDILAPPX.ps1 and distribute via email or web download.

app installs OK, but login fails with AADSTSS0011: the reply address <ms-app:different id> does not match the reply addresses configured for the application.

Is there any way to keep the redirect url constant or to explicitely specify a value to avoid this issue?

**Comment by shrimmy** [comment]
I have the same issue and would also like to be able to set this value. I am going to be outsourcing building an app for the 3 main platformas (IOS, Android & Windows) to a 3rd party organization and I think it is not a very good user experience to first build the app, debug to get the replyUrl and then register that with our app in our AAD tenant.

Hoping that there is a better solution.

**Comment by vibronet** [comment]
the reply URL is assigned by the OS, hence there's not much that can be done there. However you can always change the corresponding entry AFTER you get assigned a new value. In fact, you can have multiple values at the same time to keep the app functional in different environments and stages.

**Comment by m-bene** [comment]
One of the nasty aspects of getting a new redirect uri when signing the appx file is that you can't get the new value using the debug/breakpoint method described. 
At least the new value was displayed in the error message in the login popup, but I still had to read it off the device screen and manually type it in again. not much fun given the size of the generated redirect uris.

**Comment by jmprieur** [comment]
Archiving this sample
